import type { Metadata } from "next";
import { Poiret_One } from "next/font/google";
import "./globals.css";
import {Header, Footer } from '@/components/common';
import Head from "next/head";
// const poiret = Poiret_One({ subsets: ["latin"] });
// import '@assets/main.css'

export const metadata: Metadata = {
  title: "Clara's portfolio",
  description: "Generated by create next app",
};
const poiret = Poiret_One({
  subsets: ['latin-ext'],
  style: 'normal',
  weight: '400',
  display: 'swap',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head  /> */}
      <body className={poiret.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        </body>
    </html>
  );
}
